server :
  port : 3232


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./taskmanager_app;
  jpa:
    hibernate:
      ddl-auto: create # in prod, use update, NOT create
    show-sql: true
  h2:
    console:
      enabled: true